-- MySQL Script generated by MySQL Workbench
-- Sat Dec 13 10:31:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema milk_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `milk_project` ;

-- -----------------------------------------------------
-- Schema milk_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `milk_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `milk_project` ;

-- -----------------------------------------------------
-- Table `milk_project`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `uq_roles_role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `google_id` VARCHAR(50) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(500) NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_user_email` (`email` ASC) VISIBLE,
  INDEX `idx_google_id` (`google_id` ASC) VISIBLE,
  INDEX `fk_users_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `milk_project`.`role` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `uq_carts_user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_carts_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `milk_project`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `uq_categories_name` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`manufacturer` (
  `manufacturer_id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`manufacturer_id`),
  UNIQUE INDEX `uq_manufacturers_name` (`manufacturer_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(150) NOT NULL,
  `category_id` INT NOT NULL,
  `manufacturer_id` INT NULL DEFAULT NULL,
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `is_hot` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_products_manufacturer_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `milk_project`.`category` (`category_id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_products_manufacturers`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `milk_project`.`manufacturer` (`manufacturer_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`product_variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`product_variant` (
  `variant_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `variant_name` VARCHAR(150) NULL DEFAULT NULL,
  `volume` VARCHAR(50) NULL DEFAULT NULL,
  `packaging_type` VARCHAR(50) NULL DEFAULT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `stock_quantity` INT NULL DEFAULT '0',
  `is_active` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`variant_id`),
  INDEX `fk_product_variants_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_variants_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `milk_project`.`product` (`product_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`product_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`product_batch` (
  `batch_id` INT NOT NULL AUTO_INCREMENT,
  `variant_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT '0',
  `manufacturing_date` DATE NULL DEFAULT NULL,
  `expiration_date` DATE NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`batch_id`),
  INDEX `fk_product_batch_variants_idx` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_batch_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `milk_project`.`product_variant` (`variant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`cart_item` (
  `cart_id` INT NOT NULL,
  `variant_id` INT NOT NULL,
  `batch_id` INT NULL DEFAULT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `is_checked` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cart_id`, `variant_id`),
  INDEX `fk_cart_items_cart_idx` (`cart_id` ASC) VISIBLE,
  INDEX `fk_cart_items_variant_idx` (`variant_id` ASC) VISIBLE,
  INDEX `fk_cart_items_batch_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_items_batch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `milk_project`.`product_batch` (`batch_id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_cart_items_carts`
    FOREIGN KEY (`cart_id`)
    REFERENCES `milk_project`.`cart` (`cart_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_cart_items_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `milk_project`.`product_variant` (`variant_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`supplier` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`supplier_id`),
  UNIQUE INDEX `uq_suppliers_name` (`supplier_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NULL DEFAULT NULL,
  `total_amount` DECIMAL(12,2) NULL DEFAULT '0.00',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_invoices_suplliers_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_suplliers`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `milk_project`.`supplier` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`invoice_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`invoice_detail` (
  `invoice_detail_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `variant_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`invoice_detail_id`),
  INDEX `fk_invoice_details_invoice_idx` (`invoice_id` ASC) VISIBLE,
  INDEX `fk_invoice_details_variant_idx` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_details_invoices`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `milk_project`.`invoice` (`invoice_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_invoice_details_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `milk_project`.`product_variant` (`variant_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `status` ENUM('pending', 'processing', 'shipping', 'delivered', 'cancelled') NULL DEFAULT 'pending',
  `full_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `delivery_address` VARCHAR(255) NOT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `delivery_date` DATETIME NULL DEFAULT NULL,
  `shipping_fee` DECIMAL(12,2) NULL DEFAULT '0.00',
  `total_amount` DECIMAL(12,2) NOT NULL,
  `is_paid` TINYINT(1) NULL DEFAULT '0',
  `payment_method` ENUM('COD', 'MOMO', 'VNPAY', 'BANK_TRANSFER') NULL DEFAULT 'COD',
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `milk_project`.`user` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`order_detail` (
  `order_detail_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `variant_id` INT NOT NULL,
  `batch_id` INT NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `total_amount` DECIMAL(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_detail_id`),
  INDEX `fk_order_details_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_details_variant_idx` (`variant_id` ASC) VISIBLE,
  INDEX `fk_order_details_batch_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_batches`
    FOREIGN KEY (`batch_id`)
    REFERENCES `milk_project`.`product_batch` (`batch_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_order_details_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `milk_project`.`orders` (`order_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_order_details_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `milk_project`.`product_variant` (`variant_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  `transaction_code` VARCHAR(100) NULL DEFAULT NULL,
  `bank_code` VARCHAR(50) NULL DEFAULT NULL,
  `response_code` VARCHAR(10) NULL DEFAULT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `status` ENUM('PENDING', 'SUCCESS', 'FAILED') NULL DEFAULT 'PENDING',
  `payment_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payments_orders_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `milk_project`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`product_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`product_detail` (
  `product_id` INT NOT NULL,
  `origin` VARCHAR(255) NULL DEFAULT NULL,
  `ingredients` TEXT NULL DEFAULT NULL,
  `usage` TEXT NULL DEFAULT NULL,
  `storage` TEXT NULL DEFAULT NULL,
  `calories` DECIMAL(5,2) NULL DEFAULT '0.00',
  `protein` DECIMAL(5,2) NULL DEFAULT '0.00',
  `fat` DECIMAL(5,2) NULL DEFAULT '0.00',
  `carbohydrates` DECIMAL(5,2) NULL DEFAULT '0.00',
  `sugar` DECIMAL(5,2) NULL DEFAULT '0.00',
  `vitamins` JSON NULL DEFAULT NULL,
  `minerals` JSON NULL DEFAULT NULL,
  `other_nutrients` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `milk_project`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`promotion` (
  `promo_id` INT NOT NULL AUTO_INCREMENT,
  `promo_code` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `discount_type` ENUM('percent', 'fixed') NULL DEFAULT NULL,
  `discount_value` DECIMAL(10,2) NOT NULL,
  `max_discount_value` DECIMAL(12,2) NOT NULL,
  `min_order_value` DECIMAL(12,2) NOT NULL,
  `max_uses` INT NULL DEFAULT NULL,
  `uses_count` INT NULL DEFAULT '0',
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `created_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`promo_id`, `min_order_value`),
  UNIQUE INDEX `uq_promotions_code` (`promo_code` ASC) VISIBLE,
  INDEX `fk_promotions_created_by_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_promotions_users`
    FOREIGN KEY (`created_by`)
    REFERENCES `milk_project`.`user` (`user_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `rating` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `uq_reviews_product_user` (`product_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `fk_reviews_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_reviews_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `milk_project`.`product` (`product_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_reviews_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `milk_project`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `milk_project`.`user_promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milk_project`.`user_promotion` (
  `user_promotion_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `promo_id` INT NOT NULL,
  `used_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_promotion_id`),
  UNIQUE INDEX `uq_user_promotions_user_promo` (`user_id` ASC, `promo_id` ASC) VISIBLE,
  INDEX `fk_user_promotions_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_promotions_promo_idx` (`promo_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_promotions_promotions`
    FOREIGN KEY (`promo_id`)
    REFERENCES `milk_project`.`promotion` (`promo_id`),
  CONSTRAINT `fk_user_promotions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `milk_project`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
