-- MySQL Script generated by MySQL Workbench
-- Wed Dec  3 17:22:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema php_milk_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php_milk_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php_milk_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `php_milk_project` ;

-- -----------------------------------------------------
-- Table `php_milk_project`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `uq_role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role_id` INT NOT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_user_email` (`email` ASC) VISIBLE,
  INDEX `fk_users_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `php_milk_project`.`role` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `uq_cart_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `php_milk_project`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `uq_category_name` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(150) NOT NULL,
  `category_id` INT NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `discount_percent` INT NULL DEFAULT '0',
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `is_hot` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `php_milk_project`.`category` (`category_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`cart_item` (
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT '1',
  `is_checked` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cart_id`, `product_id`),
  INDEX `fk_cart_item_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_item_cart`
    FOREIGN KEY (`cart_id`)
    REFERENCES `php_milk_project`.`cart` (`cart_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_cart_item_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `php_milk_project`.`product` (`product_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `status` ENUM('pending', 'confirmed', 'delivered', 'cancelled') NULL DEFAULT 'pending',
  `delivery_address` VARCHAR(255) NULL DEFAULT NULL,
  `delivery_date` DATETIME NULL DEFAULT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total_amount` DECIMAL(12,2) NULL DEFAULT NULL,
  `is_paid` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `php_milk_project`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`order_detail` (
  `order_detail_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `total_amount` DECIMAL(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_detail_id`),
  INDEX `fk_order_detail_order_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_detail_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `php_milk_project`.`order` (`order_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_order_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `php_milk_project`.`product` (`product_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_method` ENUM('COD', 'MOMO', 'VNPAY', 'BANK_TRANSFER') NOT NULL DEFAULT 'COD',
  `transaction_code` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Mã giao dịch từ cổng thanh toán (VD: GD12345)',
  `amount` DECIMAL(12,2) NOT NULL COMMENT 'Số tiền thanh toán trong lần này',
  `status` ENUM('PENDING', 'SUCCESS', 'FAILED') NULL DEFAULT 'PENDING',
  `payment_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment_order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `php_milk_project`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `php_milk_project`.`product_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_milk_project`.`product_detail` (
  `product_id` INT NOT NULL,
  `ingredients` TEXT NULL DEFAULT NULL,
  `usage` TEXT NULL DEFAULT NULL,
  `storage` TEXT NULL DEFAULT NULL,
  `nutrition_info` TEXT NULL DEFAULT NULL,
  `origin` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `php_milk_project`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
